name: Github Action Practice
on: [push]
jobs:
  Explore-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ æˆåŠŸè§¸ç™¼äº‹ä»¶ ${{ github.event_name }}"
      - run: echo "ğŸ§ Job running on ${{ runner.os }} server"
      - run: echo "ğŸ§ Brench ${{ github.ref }}ï¼Œä½ çš„repoæ˜¯ ${{ github.repository }}"
      - name: Checkout repository code
        uses: actions/checkout@v2
      - run: |
        ls ${{ github.workspace }}
      - run: echo: "Job Status: ${{ job.status }}"
